[project]
name = "codeordie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agno>=1.5.6",
    "fastapi>=0.115.12",
    "googlemaps>=4.10.0",
    "groq>=0.25.0",
    "pydantic-ai>=0.2.6",
]
